import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

final ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  typography: Typography.material2021(platform: defaultTargetPlatform),
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff095d9e),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffa6cced),
    onPrimaryContainer: Color(0xff0e1114),
    secondary: Color(0xff7cc8f8),
    onSecondary: Color(0xff000000),
    secondaryContainer: Color(0xffc5e7ff),
    onSecondaryContainer: Color(0xff111314),
    tertiary: Color(0xffdd520f),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffffdbcd),
    onTertiaryContainer: Color(0xff141211),
    error: Color(0xffb00020),
    onError: Color(0xffffffff),
    errorContainer: Color(0xfffcd8df),
    onErrorContainer: Color(0xff141213),
    background: Color(0xffeaf1f7),
    onBackground: Color(0xff090909),
    surface: Color(0xffeaf1f7),
    onSurface: Color(0xff090909),
    surfaceVariant: Color(0xffd6e4ef),
    onSurfaceVariant: Color(0xff101112),
    outline: Color(0xff565656),
    shadow: Color(0xff000000),
    inverseSurface: Color(0xff10171c),
    onInverseSurface: Color(0xfff5f5f6),
    inversePrimary: Color(0xffa2d8ff),
    surfaceTint: Color(0xff095d9e),
  ),
);

final darkTheme = ThemeData(
  useMaterial3: true,
  typography: Typography.material2021(platform: defaultTargetPlatform),
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff4585b5),
    onPrimary: Color(0xfff4f9fd),
    primaryContainer: Color(0xff095d9e),
    onPrimaryContainer: Color(0xffe1eef8),
    secondary: Color(0xff9cd5f9),
    onSecondary: Color(0xff101414),
    secondaryContainer: Color(0xff3a7292),
    onSecondaryContainer: Color(0xffe8f1f6),
    tertiary: Color(0xffe57c4a),
    onTertiary: Color(0xfffff8f4),
    tertiaryContainer: Color(0xffdd520f),
    onTertiaryContainer: Color(0xffffece2),
    error: Color(0xffcf6679),
    onError: Color(0xff140c0d),
    errorContainer: Color(0xffb1384e),
    onErrorContainer: Color(0xfffbe8ec),
    background: Color(0xff14171a),
    onBackground: Color(0xffececed),
    surface: Color(0xff14171a),
    onSurface: Color(0xffececed),
    surfaceVariant: Color(0xff171e24),
    onSurfaceVariant: Color(0xffdadbdc),
    outline: Color(0xff9d9da3),
    shadow: Color(0xff000000),
    inverseSurface: Color(0xfff4f7fa),
    onInverseSurface: Color(0xff131313),
    inversePrimary: Color(0xff2c485d),
    surfaceTint: Color(0xff4585b5),
  ),
);
