name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.2
  dotenv: ^4.1.0
  mongo_dart: ^0.8.2
  mongo_dart_query: ^3.0.0

  shared:
    path: ./packages/shared

dev_dependencies:
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
